//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthExercise.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Info
    {
        public int User_ID { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string Phone { get; set; }
        public string Category { get; set; }
    
        public virtual User User { get; set; }
    }
}
